name = "hisobkit-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding      = "DB"
database_name = "hisobkit-db"
database_id  = "75c5f61c-1ef6-490d-86ee-d6efd4a55219"

[[kv_namespaces]]
binding = "AUTH_KV"
id      = "69e6946ab168414c924dbd7669a50ada"

[vars]
APP_NAME          = "HisobKit"
ACCESS_TOKEN_TTL  = "900"
REFRESH_TOKEN_TTL = "2592000"
OTP_TTL           = "300"
OTP_MAX_ATTEMPTS  = "3"
RATE_LIMIT_WINDOW = "60"

# Secrets (wrangler secret put orqali qo'shiladi):
# JWT_SECRET
# GOOGLE_CLIENT_ID
# RESEND_API_KEY
# RESEND_FROM_EMAIL
